  confirm: 'Confirm',
  cancel: 'Cancel',
  goBack: 'Return',
  delete: 'Delete',
  goBack: 'return',
  canceled: 'Canceled',
  hint: 'Hint',
  add: 'Add',
  ServerException: 'The server is abnormal. Please shut it down and restart it',
    current: 'Current',
    unitException: 'Device abnormal ',
    zh: 'Chinese',
    en: 'English',
    levitatedSphere: 'Levitated Sphere',
    systemSetup: 'System settings',
    switched: 'Switch system',
    logOut: 'Log Out',
    AreYoutoQuit: 'Quit?',
    quitSucceed: 'Quit succeed',
    CPUt: 'CPU Temp',
    setSystem: 'System settings',
    LogSaving: 'Log saving time',
    TCPinterval: 'TCP Interval      ',
    day: 'Day',
    minute: 'Minute',
    AlarmRecording: 'Alarm records',
    export: 'Export',
    nameExhibitionHall: 'Name/Exhibition Hall',
    codeOfError: 'Error',
    issue: 'Issue',
    startingTime: 'Starting Time',
    continueTime: 'Continue Time',
    devSn: 'Device SN',
    asRegards: 'As Regards',
    versionNumber: 'Version Number',
    GroupIs: 'Groups',
    StatusIs: 'Projector Type',
    drawing: 'Drawings',
    control: 'Control',
    info: 'Info',
    schedule: 'Schedule',
    InstallAdjustment: 'Installation Adjustment',
    project: 'Project',
    factory: 'Factory'
    projector: 'Projector',
    projectorAdd: 'Add projector',
    projectoredit: 'Edit projector',
    custom: 'Custom',
    groupingOfProjector: 'Grouping Projector',
    groupingOfProjectorText: 'Please select projector group',
    edit: 'Edit',
    establish: 'Create',
    aircraftType: 'Projector Type',
    aircraftTypeText: 'Please select model',
    controlMode: 'Control Mode',
    controlModeText: 'Please select control mode',
    networkSettings: 'Network settings',
    IPAddress: 'IP Site',
    portNumber: 'Port Number',
    portNumberText: 'Please input port number',
    serialPort: 'Serial Port',
    serialPortCircuit: 'Serial Port Path',
    serialPortCircuitText: 'Please select serial port path',
    BaudRate: 'Baud Rate',
    BaudRateText: 'Please input baud rate',
    projectorID: 'Projector ID',
    projectorText: 'Please input projector ID',
    accessProtocol: 'Access Protocol',
    accessProtocolText: 'Please select access protocol',
    name: 'Projector name',
    nameText: 'Please input projector name',
    completeInfo: 'Please complete projector info',
    automaticSearch: 'Auto Search',
    searchDuration: 'Search Duration',
    minute: 'Minute',
    default: 'Default',
    searchAgain: 'Search again',
    startSearch: 'Start search',
    searchDev: 'Search Device',
    fastSearch: 'Fast searching for projectors',
    collectTheseDev: 'Found the following devices',
    suspendSearch: 'Pause search',
    IgnoreItAll: 'Ignore all',
    collectDev: 'Device found',
    devIp: 'Device IP',
    operate: 'Operate',
    loseSight: 'Ignore',
    haveSucceeded: 'Succeed',
    viewDetails: 'View Details',
    devInfo: 'projector info',
    createAnotherOne: 'Create another one',
    reedit: 'Re-edit',
    toGroup: 'Move to group',
    creatingGroup: 'New group',
    addToGroup: 'Add to new group',
    toHereGroup: 'Move to current group',
    MakeSureToDeleteTheSelectedOne: 'Confirm delete the selected',
    EachGroupAndWithinTheGroup: 'Each group and within the group',
    IsItAProjector: 'Is it a projector',
    ren: 'Rename',
    renLength: 'Length should be 1 to 30',
    renText: 'Please input new name',
    newSchedule: 'New schedule',
    exectorial: 'Command execution',
    exectorialText: 'Command execution',
    startTime: 'Start Time',
    startTimeText: 'Please select start time',
    finishTime: 'Finish time',
    finishTimeText: 'Please select finish time',
    repetition: 'Repetition',
    repetitionText: 'Please select repetition texts',
    ParticipateMachine: 'Participating machines',
    ParticipateMachineText: 'Please select participating machines',
    addGroup: 'New Group',
    renGroup: 'Rename Group',
    startingUp: 'Turn On',
    shutdown: 'Turn Off',
    onSwitch: 'Shutter On',
    offSwitch: 'Shutter Off',
    schedule: 'Schedule',
    log: 'Log',
    renProjector: 'Rename projector',
    CreateNewprojector: 'New projector',
    SearchForProjectorsGroups: 'Search for projector groups',
    new: 'New',
    deviceState: 'Device State',
    TimeOnLine: 'Online runtime',
    TimeOffLine: 'Offline runtime',
    modelName: 'Model name',
    IPSite: 'IP Site',
    projectorID: 'Projector ID',
    NumberOfFailedLayersToCreate:
      'Create failed! Support maxinum 8 layers nestification',
    successfullyCreated: 'Successfully created',
    selectTheGroupOrDevice: 'Please first select group or device',
    enterANewGroupName: 'Please enter new group name',
    successfulMove: 'Move succeed',
    CancelAMove: 'Cancel move',
    PleaseSelectaGroup: 'Please select a group',
    TheNameCannotContainSpaces: 'Name cannot contain spaces',
    modifySuccessfully: 'Modify succeed',
    successfullyDelete: 'Delete succeed',
    WhetherToMoveTheNodeTo: 'Move node to',
    before: 'Before',
    after: 'After',
    inner: 'Inner',
    IncorrectIpAddressInput: 'Incorrect IP input',
    TheProjectorNameCannotContainSpaces: 'Projector name cannot contain space',
    ProjectorNameLength: 'Length should be 1 to 30',
    EditingSuccess: 'Editing Success',
    AddingSuccess: 'Adding succeed'
    title: 'Title',
    exhibitionHall: 'Exhibition Hall',
    powerSupply: 'Power',
    startingUp: 'Turn On',
    shutdown: 'Turn Off',
    shutter: 'Shutter',
    on: 'On',
    off: 'Off',
    connect: 'Connect',
    networkUnunited: 'Network not connect',
    networkConnected: 'Network Connected',
    RS232Ununited: 'RS232 not connect',
    RS232Connected: 'RS232 connected',
    informationSource: 'Signal Source',
    noSignal: 'No signal',
    operationTime: 'System/Light source run time',
    temperature: 'Temperature',
    error: 'Error',
    operation: 'Operate',
    look: 'Check',
    refresh: 'Refresh'
    startingUp: 'Turn On',
    shutdown: 'Turn Off',
    onShutter: 'Turn Shutter On',
    offShutter: 'Turn Shutter Off',
    off: 'Off',
    sideView: 'Test Picture',
    gridding: 'Gridding',
    white: 'White',
    red: 'Red',
    green: 'Green',
    blue: 'Blue',
    black: 'Black',
    equipmentMonitoring: 'Equipment Monitor',
    refresh: 'Refresh',
    platform: 'Platform',
    TotalNumberOfEquipment: 'Total Number Of Equipments',
    NumberOfOnlineDevices: 'Number Of Online Devices',
    NumberOfOfflineDevices: 'Number Of Offline Devices',
    AbnormalEquipment: 'Abnormal Equipments'
    calendar: 'Calendar',
    MySchedule: 'My Schedule',
    ExecutedSchedule: 'Executed schedule',
    scheduleOn: 'Schedule On',
    scheduleOff: 'Schedule Off',
    taskList: 'Task List',
    addSchedule: 'New schedule'
    TheDeviceIsSelectedProcedure: 'Current selected device',
    model: 'Model',
    lensToAdjust: 'Lens Adjustment',
    visionControl: 'Picture adjustment',
    colourControl: 'Color Adjustment',
    PictureClipping: 'Picture crop',
    distortionCorrection: 'Distortion correction',
    sign: 'Signal',
    powerSupply: 'Installation Setup',
    universal: 'Settings',
    network: 'Network'
    devError: 'The device does not support this operation',
    zoom: 'Zoom',
    scaling: 'Scaling',
    trimming: 'Fine tuning',
    coarseTuning: 'Coarse tuning',
    AutomaticCenter: 'Auto Center',
    shutter: 'Shutter',
    MeasureView: 'Test Picture',
    AdjustmentOfLens: 'Lens Adjustment',
    displacement: 'Displacement',
    off: 'Off',
    gridding: 'Gridding',
    white: 'White',
    red: 'Red',
    green: 'Green',
    blue: 'Blue',
    cyan: 'Cyan',
    magenta: 'Magenta',
    yellow: 'Yellow',
    black: 'Black',
    sixteenGrayScale: 'Sixteen Gray Scale',
    twentyFiveGrayScale: '256 Gray Scale',
    colourBar: 'Color Bar',
    rgbRamp: 'RGB Ramp',
    checkerboard: 'Checkerboard'
    restoreDefault: 'Restore default',
    sceneModel: 'Scene Mode',
    acutance: 'Sharpness',
    temperatureAdjusting: 'Color temp adjustment',
    redGain: 'Red Gain',
    greenGain: 'Green gain',
    contrastEnhancement: 'Contrast Enhancement',
    blueGain: 'Blue gain',
    luminance: 'Brightness',
    contrast: 'Contrast',
    saturability: 'Saturation',
    gammaAdjust: 'Gamma Adjustment',
    DynamicContrastRatio: 'Dynamic Contrast',
    ImageScale: 'Display Ratio'
    redColor: 'Red Tone',
    RedSaturation: 'Red Saturation',
    GreenHue: 'Green Hue',
    GreenSaturation: 'Green Saturation',
    BlueHue: 'Blue Hue',
    BlueSaturation: 'Blue Saturation',
    whiteColor: 'White Hue',
    red: 'Red',
    green: 'Green',
    blue: 'Blue',
    MagentaColor: 'Magenta Hue',
    MagentaSaturation: 'Magenta Saturation',
    YellowColor: 'Yellow hue',
    YellowSaturation: 'Yellow Saturation',
    CyanColor: 'Cyan Ton',
    CyanSaturation: 'Cyan Saturation',
    visualFeast: 'Visual enhancement',
    Magentagain: 'Magenta gain',
    Redgain: 'Red Gain',
    Greengain: 'Green gain',
    Yellowgain: 'Yellow Gain',
    Bluegain: 'Blue gain',
    Cyangain: 'Cyan gain',
    restoreDefault: 'Restore default'
    ImageScale: 'Display Ratio',
    wayInstall: 'Installation method',
    projectorID: 'Projector ID',
    remoteControlID: 'Remote Control ID',
    remoteControlReceiving: 'Remote Control Receiving',
    threeColourConverge: 'Three colors converge',
    restoreDefault: 'Restore default'
    Powerondefaultsource: 'Defaul power on source',
    Sourceselection: 'Source selection',
    blankScreen: 'Blank Screen',
    automaticSearch: 'Auto Search',
    automaticAdjustment: 'Auto Adjustment',
    VGASet: 'VGA Settings',
    Horizontalposition: 'Horizontal position',
    Verticalposition: 'Vertical position',
    phasePosition: 'Phase Position',
    clock: 'Clock',
    colorspace: 'Color Space',
    Signallevelrange: 'Signal level range',
    HDMISet: 'HDMI Settings',
    threeDSet: '3D Settings',
    threeModle: '3D Mode',
    threeLayout: '3D Format',
    leftRgihtEyeReversal: 'Left/Rgiht eye normal',
    delayAdjust: 'Sync-delay adjustment',
    leftRgihtEyeDelay: 'Left/Rgiht eye delay',
    darkTime: 'Dark field time',
    selfMotion: 'Auto',
    off: 'Off',
    on: 'On',
    ReversalLeftRgihtEye: 'Left/Rgiht eye reverse',
    normalLeftRgihtEye: 'Left/Rgiht eye normal',
    restoreDefault: 'Restore default'
    powerSet: 'Power Settings',
    standbyMode: 'Standby Mode',
    AutomaticStandby: 'Auto Standby',
    startingSet: 'Power on settings',
    HighAltitudeModel: 'High altitude mode',
    runningMode: 'Operation Mode',
    custom: 'Custom',
    beInCommonUse: 'Common',
    DS: 'DS',
    SystemSoftwareUpgrade: 'System Upgrade',
    mensSet: 'Menu Setting',
    mensLanguage: 'Menu Language',
    mensLocation: 'Menu position',
    UpgradeImmediately: 'Upgrade immediately',
    NoSignalPrompt: 'No Signal Prompt',
    AutomaticMenuExit: 'Automatic menu exit',
    HiddenMenu: 'Hidden Menu',
    volume: 'Volume',
    mute: 'Mute',
    lowPower: 'Low Power',
    networking: 'Network',
    minute: 'Minute',
    Manual: 'Manual',
    PowerOnAutomatically: 'Auto PowerOn',
    WakeUpAutomaticallyOnSignal: 'Auto wake up on signal',
    TheProjectorUploadsTothePC: 'Projector uploads to PC',
    TheUpperComputerIsSentToTheProjector: 'Upper computer sent to projector',
    Upperleft: 'Upper left',
    centreTop: 'Central Top',
    Upperright: 'Upper right',
    Middleleft: 'Middle-left',
    Center: 'Center',
    Rightmiddle: 'Middle-right',
    Lowerleft: 'Lower left',
    centrelower: 'Lower Central',
    lowerright: 'Lower right',
    show: 'Display',
    hide: 'Hide',
    off: 'Off',
    on: 'On',
    restoreDefault: 'Restore default'
    PleaseLogInFirst: 'Please login',
    PleaseSelectTheDevice: 'Please select the device'
